### DISCUSSION TITLE
Adding a Favicon.

### DISCUSSION THREAD

**Discussion by g-pacheco** [athul/archie#43] [Q&A] [answered]
Dear Archie,

I have been wondering what would be the best way of having a favicon to the Archie theme. I had tried to add something like the following to the `head.html` to no avail:

```
<link rel="apple-touch-icon" sizes="180x180" href="../../../../content/Favicon/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="../../../../content/Favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="../../../../content/Favicon/favicon-16x16.png">
<link rel="manifest" href="../../../../content/Favicon/site.webmanifest">
<link rel="mask-icon" href="../../../../content/Favicon/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
```

I have also noticed this piece of code in the `header.html` file, but it is not clear to me how a favicon should be properly added.

```
{{- if isset .Site.Params "favicon" -}}
<link rel="icon" type="image/png" href={{ .Site.Params.favicon }} />
{{- end -}}
```

I would appreciate any help.

Many thanks in advance, George.

**Comment by athul** [comment, marked as answer]
Hey, sorry for the late reply, You can add a favicon by adding the path to favicon in the config.toml file under `[params]`. Here is an example of the demo site's config.toml file

https://github.com/athul/archie/blob/04e48d996f4173a2c7918c4941ff5952e1febb08/config.toml#L12

```toml
baseURL = "https://athul.github.io/archie/"
languageCode = "en-us"
title = "Archie"
theme = "archie"
copyright = "© Athul"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
paginate = 4

[params]
favicon = "https://img.icons8.com/officel/16/000000/chevron-right.png"
og_image = "https://raw.githubusercontent.com/athul/archie/master/images/archie-dark.png"
# mode = "auto"
mode = "toggle"
useCDN = true
subtitle = "Minimal and Clean [blog theme for Hugo](https://github.com/athul/archie)"
description = "Archie is a Minimal and Clean theme for Hugo"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/athul/archie"

...
```
