### ISSUE TITLE
Add support for rst tables

### ISSUE THREAD

**Issue by FFY00** [athul/archie#10]
Hi, I am interested in using this theme with restructuredText. Everything looks pretty good other than the tables, which are not stylized. Would it be possible to add support for this?

Example:
```rst
== ====
ID Text
== ====
 0   a
 1   b
 2   c
 3   d
== ====



.. table:: Table 1 - Packet structure

    +-------------+-----------+--------------+---------------+------------------------+------------+
    |     byte    |     0     |       1      |       2       |            3           |  4 .. End  |
    +-------------+-----------+--------------+---------------+----------+-------------+------------+
    |     bit     |                                          |  15 .. 8 |    7 .. 0   |            |
    +=============+===========+==============+===============+==========+=============+============+
    | description | Report ID | Device Index | Feature Index | Function | Software ID | Parameters |
    +-------------+-----------+--------------+---------------+----------+-------------+------------+
```

**Comment by athul** [comment]
I'm really sorry, I've never used rst before and the Hugo supports it but it is not that docs which reduces the chances for me to push an  update regarding this. But you could use hugo shortcodes for rendering tables from rst to html.
Here is the link to Hugo's Doc for Shortcodes → https://gohugo.io/templates/shortcode-templates/#readout

**Comment by FFY00** [comment]
I adapted the theme with the following css. It hides the borders and fills the cells.

```css
table {
  border-color: transparent;
}
th {
  border-color: transparent;
  background-color: rgba(0, 0, 0, 0.2);
}
td {
  border-color: transparent;
  background: rgba(0, 0, 0, 0.1);
}
```
