### ISSUE TITLE
No social icons?

### ISSUE THREAD

**Issue by BuyMyMojo** [athul/archie#39]
For some reason the social icons aren't appearing

Page: https://buymymojo.gitlab.io/buymymojo-hugo/

config:
```toml
baseurl = "https://buymymojo.gitlab.io/buymymojo-hugo/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "BuyMyMojo"
copyright = "© BuyMyMojo"

DefaultContentLanguage = "en-us"
theme = "archie"
metaDataFormat = "yaml"

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableEmoji = true
enableRobotsTXT = true

paginate=2

[Author]
name = "Owen Quinlan"
email = "hello@buymymojo.net"
gitlab = "BuyMyMojo"
github = "BuyMyMojo"
linkedin = "owen-quinlan-b6b6431b7"
keybase = "bmmojo"

[sitemap]
    changefreq = 'daily'
    filename = 'sitemap.xml'
    priority = 0.5

[Params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
    subtitle = "Mojos for the masses" # This sub title was generated by github copilot lmao
    logo = "img/avatar-icon.png"
    favicon = "img/favicon.ico"
    dateFormat = "January 2, 2006"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/BuyMyMojo/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/OwenQuinlan7/"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/BuyMyMojo/"


[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "page/about/"
weight = 3

[[menu.main]]
name = "Tags"
url = "tags"
weight = 4

```
