### ISSUE TITLE
error in feather.min.js path in header.html

### ISSUE THREAD

**Issue by sebasrp** [athul/archie#84]
When using a social tag and using local js libraries, there is an error loading feather.min.js

```toml
[params]
	useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/sebasr"
```

Error encountered when loading the root page

```bash
sebasr.com/:1     GET https://sebasr.comjs/feather.min.js net::ERR_NAME_NOT_RESOLVED
(index):29 Uncaught ReferenceError: feather is not defined
    at (index):29:182
(anonymous) @ (index):29
```
